import { NextResponse } from 'next/server';
import { doc, setDoc } from 'firebase/firestore';
import { db } from '../../../utils/firebase'; // Ensure this path is correct!

const inventoryData = [
  // MICROCONTROLLERS (9)
  { id: 1, name: 'Arduino Uno R3', price: 350, discount: '20', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/51tE5E+kK1L.jpg', icon: 'fa-microchip', desc: 'Industry standard ATmega328P microcontroller board ideal for rapid prototyping and automation logic.', details: '• Microcontroller: ATmega328P\n• Operating Voltage: 5V\n• Input Voltage: 7-12V\n• Digital I/O Pins: 14', componentsList: null, variants: null, stock: 50 },
  { id: 2, name: 'Arduino Nano V3', price: 160, discount: '32', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/51badOM+-CL.jpg', icon: 'fa-memory', desc: 'Compact ATmega328 development board with integrated USB to serial conversion for space constrained projects.', details: '• Microcontroller: ATmega328\n• Architecture: AVR\n• Flash Memory: 32 KB\n• SRAM: 2 KB', componentsList: null, variants: null, stock: 50 },
  { id: 3, name: 'Arduino Mega 2560', price: 600, discount: '25', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/71X8kXq1w3L.jpg', icon: 'fa-server', desc: 'High performance ATmega2560 microcontroller offering expanded digital and analog IO capabilities.', details: '• Microcontroller: ATmega2560\n• Digital I/O Pins: 54\n• Analog Input Pins: 16\n• Flash Memory: 256 KB', componentsList: null, variants: null, stock: 50 },
  { id: 4, name: 'ESP8266 NodeMCU', price: 180, discount: '20', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/51k1A1u-M-L.jpg', icon: 'fa-wifi', desc: 'Versatile ESP8266 based WiFi development board engineered for seamless IoT integration.', details: '• Wi-Fi Module: ESP-12E\n• USB-TTL: CP2102\n• Power Input: 4.5V ~ 9V\n• Logic Level: 3.3V', componentsList: null, variants: null, stock: 50 },
  { id: 16, name: 'ESP32 Dev Module', price: 300, discount: '26', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/51v1zV1-m8L.jpg', icon: 'fa-broadcast-tower', desc: 'Advanced dual core ESP32 module featuring integrated WiFi and Bluetooth BLE for wireless architectures.', details: '• Processors: Dual-Core 32-bit LX6\n• Clock Speed: 240 MHz\n• Connectivity: WiFi + Bluetooth\n• RAM: 512 KB', componentsList: null, variants: null, stock: 50 },
  { id: 18, name: 'Raspberry Pi 4 (4GB)', price: 4800, discount: '10', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/71a2B6I1-xL.jpg', icon: 'fa-usb', desc: 'Robust single board computer powered by Broadcom BCM2711 delivering desktop grade edge computing.', details: '• Processor: Broadcom BCM2711\n• RAM: 4GB LPDDR4 SDRAM\n• Connectivity: Bluetooth 5.0 with BLE', componentsList: null, variants: null, stock: 50 },
  { id: 19, name: 'ATTiny85 Digispark', price: 120, discount: '30', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/51Z-W-+23fL.jpg', icon: 'fa-bolt', desc: 'Ultra compact ATTiny85 development board featuring a direct USB interface for minimalist solutions.', details: '• Flash Memory: 8k\n• I/O Pins: 6\n• Interface: Hardware USB', componentsList: null, variants: null, stock: 50 },
  { id: 17, name: 'Raspberry Pi Pico', price: 300, discount: '20', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/51fG1O2h2WL.jpg', icon: 'fa-microchip', desc: 'High performance microcontroller board built on the RP2040 silicon featuring flexible PIO state machines.', details: '• Chip: RP2040\n• Cores: Dual-core Arm Cortex M0+\n• Clock Speed: 133 MHz', componentsList: null, variants: null, stock: 50 },
  { id: 54, name: 'Raspberry Pi Zero 2 W', price: 1500, discount: '35', category: 'microcontrollers', rating: 0, image: 'https://m.media-amazon.com/images/I/61VdGIfU1GL.jpg', icon: 'fa-memory', desc: 'Highly efficient single board computer equipped with wireless LAN and Bluetooth connectivity.', details: '• Processor: Broadcom BCM2710A1\n• RAM: 512 MB LPDDR2 SDRAM\n• Connectivity: Wireless LAN & BLE', componentsList: null, variants: null, stock: 50 },

  // TOOLS (10)
  { id: 60, name: 'Soldering Iron (60W)', price: 120, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/61BZLe4H9oL.jpg', icon: null, desc: 'Professional 60W thermal heating element designed for precision electronic component soldering.', details: '• Power Rating: 60W\n• Input Voltage: 220V AC\n• Tip Type: Interchangeable conical', componentsList: null, variants: null, stock: 50 },
  { id: 61, name: 'Digital Multimeter', price: 150, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/61MvJ+K6VGL.jpg', icon: null, desc: 'High accuracy digital multimeter for voltage, current, and resistance diagnostic testing.', details: '• Display: 3½ digit LCD\n• Measurements: AC/DC Voltage, DC Current, Resistance\n• Extras: Diode and Continuity test', componentsList: null, variants: null, stock: 50 },
  { id: 62, name: 'Wire Stripper', price: 40, discount: '15', category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/61n-YVWT4pL.jpg', icon: null, desc: 'Ergonomic carbon steel wire stripping tool for rapid and clean insulation removal.', details: '• Material: Hardened Carbon Steel\n• Handle: Insulated ergonomic grip\n• Function: Stripping and flush cutting', componentsList: null, variants: null, stock: 50 },
  { id: 63, name: 'Soldering Stand', price: 60, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/611fIPQi0tL.jpg', icon: null, desc: 'Heavy-duty metal base soldering iron stand featuring an integrated cleaning sponge.', details: '• Base: Heavy-duty cast iron\n• Holder: Spring-style funnel\n• Accessories: Integrated cleaning sponge', componentsList: null, variants: null, stock: 50 },
  { id: 64, name: 'Desoldering Pump', price: 50, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/51Z-W-+23fL.jpg', icon: null, desc: 'High suction vacuum desoldering pump with a heat resistant teflon tip for circuit repair.', details: '• Mechanism: High-suction spring vacuum\n• Material: Aluminum body\n• Tip: Heat-resistant replaceable Teflon', componentsList: null, variants: null, stock: 50 },
  { id: 65, name: 'Solder Wire (50g)', price: 40, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/61jH83y98mL.jpg', icon: null, desc: 'Premium 60/40 tin lead rosin core solder wire for optimal electrical conductivity.', details: '• Alloy: 60% Tin / 40% Lead\n• Core: Premium rosin flux\n• Diameter: 0.8mm\n• Weight: 50g', componentsList: null, variants: null, stock: 50 },
  { id: 66, name: 'Hot Glue Gun', price: 120, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/618L6ygDkoL.jpg', icon: null, desc: 'Industrial grade thermal glue applicator for rapid structural bonding and component mounting.', details: '• Power Rating: 40W\n• Heating Element: PTC ceramic\n• Included: 5x transparent glue sticks', componentsList: null, variants: null, stock: 50 },
  { id: 67, name: 'Precision Screwdriver Set', price: 110, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/71lwyj4rjmL.jpg', icon: null, desc: 'Comprehensive precision magnetic screwdriver toolkit designed for complex hardware assembly.', details: '• Bits Included: Phillips, Torx, Slotted, Hex\n• Handle: Non-slip magnetic grip\n• Case: Hard plastic organizer', componentsList: null, variants: null, stock: 50 },
  { id: 68, name: 'ESD Tweezer Set', price: 80, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/61xSRrShxnL.jpg', icon: null, desc: 'Anti-static ESD safe tweezer collection engineered for safe SMD component handling.', details: '• Coating: Anti-static ESD safe\n• Material: Non-magnetic stainless steel\n• Quantity: 6 assorted tip profiles', componentsList: null, variants: null, stock: 50 },
  { id: 69, name: 'Helping Hands', price: 180, discount: null, category: 'tools', rating: 0, image: 'https://m.media-amazon.com/images/I/61sJ-A2U+xL.jpg', icon: null, desc: 'Adjustable dual clip soldering station equipped with a high magnification optical lens.', details: '• Base: Heavy cast iron for stability\n• Clips: Dual adjustable alligator clamps\n• Optics: 2x magnification glass lens', componentsList: null, variants: null, stock: 50 },

  // COMPONENTS
  { id: 5, name: 'Ultrasonic Sensor', price: 50, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51Y7WdG0tGL.jpg', icon: 'fa-satellite-dish', desc: 'Precision HC-SR04 acoustic transducer module for non-contact distance measurement.', details: '• Range: 2cm to 400cm\n• Operating Voltage: 5V\n• Resolution: 3mm', componentsList: null, variants: null, stock: 50 },
  { id: 6, name: 'Servo Motor SG90', price: 60, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51+sP1W2vBL.jpg', icon: 'fa-cogs', desc: 'Compact 180 degree micro servo motor offering a high torque to weight ratio for robotics.', details: '• Torque: 1.8 kgf·cm\n• Weight: 9g\n• Operating Angle: 180 Degrees', componentsList: null, variants: null, stock: 50 },
  { id: 7, name: 'Jumper Wires (40pcs)', price: 50, discount: '25', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/71hO0a2o+6L.jpg', icon: 'fa-random', desc: 'Flexible premium copper jumper cables optimized for solderless breadboard prototyping.', details: '• Length: 20cm\n• Quantity: 40 wires/strip\n• Pitch: Standard 2.54mm', componentsList: null, variants: ['Male-to-Male', 'Male-to-Female', 'Female-to-Female'], stock: 50 },
  { id: 8, name: 'IR Sensor Module', price: 25, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51QoI9mQ-BL.jpg', icon: 'fa-eye', desc: 'Infrared proximity and obstacle detection module with adjustable sensitivity calibration.', details: '• Detection Distance: 2-30cm\n• Output: Digital (0/1)\n• Chipset: LM393 Comparator', componentsList: null, variants: null, stock: 50 },
  { id: 9, name: 'Relay Module 1-CH', price: 35, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61YuLB9GbuL.jpg', icon: 'fa-toggle-on', desc: 'Opto-isolated single channel relay module for secure high voltage load switching.', details: '• Load Capacity: 250V AC / 10A\n• Trigger Current: 5mA\n• Isolation: Optocoupler', componentsList: null, variants: null, stock: 50 },
  { id: 47, name: 'Relay Module 4-CH', price: 120, discount: '30', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61qJ+zU44XL.jpg', icon: 'fa-server', desc: 'Industrial four channel 5V relay matrix featuring independent optocoupler isolation.', details: '• Channels: 4 Independent Relays\n• Load: 250V 10A per channel\n• Isolation: Optocoupler', componentsList: null, variants: null, stock: 50 },
  { id: 10, name: 'L293D Motor Shield', price: 100, discount: '15', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61rIVgC19bL.jpg', icon: 'fa-car-battery', desc: 'Dual H-bridge motor driver shield capable of bidirectional DC motor control.', details: '• Chip: L293D Dual H-Bridge\n• Drive Voltage: 5-35V\n• Peak Current: 1.2A per channel', componentsList: null, variants: null, stock: 50 },
  { id: 33, name: 'BO Motor with Wheel', price: 60, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61KqP-c84cL.jpg', icon: 'fa-car', desc: 'High traction dual axis TT motor and wheel assembly designed for mobile robotic chassis.', details: '• Type: TT Motor (Dual Axis)\n• Operating Voltage: 3V-6V DC\n• Gear Ratio: 1:48', componentsList: null, variants: null, stock: 50 },
  { id: 34, name: 'Mini Submersible Pump', price: 60, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51-mK9q5-cL.jpg', icon: 'fa-car', desc: 'Submersible low voltage fluid routing pump engineered for automated irrigation systems.', details: '• Flow Rate: 80 to 120 L/Hr\n• Operating Voltage: 3V-6V DC\n• Submersible: Yes', componentsList: null, variants: null, stock: 50 },
  { id: 35, name: 'L298N Motor Driver', price: 110, discount: '25', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61q3+HDNx3L.jpg', icon: 'fa-car', desc: 'High power dual channel motor controller module utilizing the L298N silicon architecture.', details: '• Chip: L298N Dual H-Bridge\n• Logic Voltage: 5V\n• Drive Voltage: 5V-35V\n• Max Current: 2A', componentsList: null, variants: null, stock: 50 },
  { id: 36, name: 'MQ-3 Alcohol Sensor', price: 80, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51tW3E5I5FL.jpg', icon: 'fa-car', desc: 'Highly sensitive semiconductor sensor calibrated for precise volatile vapor detection.', details: '• Detection Profile: Alcohol Vapor\n• Limit: 0.04 mg/L - 4 mg/L\n• Operating Voltage: 5V', componentsList: null, variants: null, stock: 50 },
  { id: 11, name: 'LCD Display 16x2', price: 90, discount: '15', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61f4V8P8R+L.jpg', icon: 'fa-tv', desc: 'High contrast alphanumeric liquid crystal display with integrated LED backlighting.', details: '• Format: 16 Characters x 2 Lines\n• Backlight: High Contrast Green/Blue\n• Interface: Parallel', componentsList: null, variants: null, stock: 50 },
  { id: 52, name: 'OLED Display 0.96"', price: 150, discount: '20', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51POYIrqBsL.jpg', icon: 'fa-tv', desc: 'Ultra crisp 128x64 pixel I2C OLED display offering deep black levels and low power draw.', details: '• Resolution: 128x64 Pixels\n• Interface: I2C\n• Driver IC: SSD1306', componentsList: null, variants: null, stock: 50 },
  { id: 12, name: 'Bluetooth HC-05', price: 180, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51oV7e8Q8tL.jpg', icon: 'fa-bluetooth', desc: 'Reliable Bluetooth V2.0 SPP module for establishing transparent wireless serial connections.', details: '• Protocol: Bluetooth V2.0+EDR\n• Range: 10 meters\n• Interface: Serial UART', componentsList: null, variants: null, stock: 50 },
  { id: 20, name: 'DHT11 Sensor', price: 45, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51y1Ww1X7bL.jpg', icon: 'fa-temperature-high', desc: 'Calibrated digital temperature and humidity sensor providing reliable environmental telemetry.', details: '• Temperature Range: 0-50°C\n• Humidity Range: 20-90% RH\n• Accuracy: ±2°C / ±5% RH', componentsList: null, variants: null, stock: 50 },
  { id: 37, name: 'PIR Motion Sensor', price: 45, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51j1-u1K+sL.jpg', icon: 'fa-walking', desc: 'Passive infrared motion detector module featuring adjustable delay and range parameters.', details: '• Delay Time: Adjustable (0.3s - 18s)\n• Detection Range: 3-7 meters\n• Angle: <120 degrees', componentsList: null, variants: null, stock: 50 },
  { id: 48, name: 'Piezo Buzzer (5V)', price: 10, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51v1-xQ8s3L.jpg', icon: 'fa-volume-up', desc: 'High decibel 5V active piezoelectric acoustic transducer for system alerts and alarms.', details: '• Voltage: 5V DC\n• Type: Active Piezoelectric\n• Output: 85dB Audio', componentsList: null, variants: null, stock: 50 },
  { id: 49, name: 'Rain Sensor Module', price: 35, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61uA4P-uO8L.jpg', icon: 'fa-cloud-rain', desc: 'Conductive precipitation detection array outputting both analog and digital signals.', details: '• Output: Dual (Analog & Digital)\n• Comparator: LM393\n• Surface: Nickel Plated', componentsList: null, variants: null, stock: 50 },
  { id: 50, name: 'Sound Sensor', price: 30, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51WfF-L+J4L.jpg', icon: 'fa-microphone', desc: 'Acoustic detection module utilizing an electret microphone and LM393 voltage comparator.', details: '• Mic Type: Electret Condenser\n• Output: Digital Threshold\n• Comparator: LM393', componentsList: null, variants: null, stock: 50 },
  { id: 21, name: 'Breadboard 830', price: 60, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61WfB3wY9XL.jpg', icon: 'fa-border-all', desc: 'Standard 830 tie point solderless breadboard engineered for rapid circuit iteration.', details: '• Points: 830 Tie-Points\n• Power Rails: 4 Independent\n• Type: MB-102 Standard', componentsList: null, variants: null, stock: 50 },
  { id: 22, name: 'LED Pack (30pcs)', price: 25, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61p-R+mG-QL.jpg', icon: 'fa-lightbulb', desc: 'Assorted high luminosity 5mm light emitting diodes for visual system diagnostics.', details: '• Size: 5mm Diffused\n• Colors: Red, Green, Yellow, Blue\n• Quantity: 30 Pieces', componentsList: null, variants: null, stock: 50 },
  { id: 23, name: 'Resistor Kit (100pcs)', price: 30, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/71aedKJXIVL.jpg', icon: 'fa-grip-lines', desc: 'Comprehensive carbon film passive resistor assortment covering standard ohm values.', details: '• Wattage: 1/4W\n• Tolerance: ±5%\n• Type: Carbon Film', componentsList: null, variants: null, stock: 50 },
  { id: 41, name: 'Ceramic Capacitors (Pack)', price: 25, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61+oJp9D8hL.jpg', icon: 'fa-microchip', desc: 'Assorted non polarized ceramic capacitors for high frequency noise decoupling.', details: '• Voltage Rating: 50V\n• Type: Non-Polarized\n• Values: Assorted standard pF/nF', componentsList: null, variants: null, stock: 50 },
  { id: 42, name: 'Electrolytic Capacitors', price: 30, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61p11P-E2kL.jpg', icon: 'fa-battery-quarter', desc: 'High capacity polarized electrolytic capacitors essential for power supply filtering.', details: '• Voltage Rating: 16V-25V\n• Type: Polarized\n• Values: Assorted standard µF', componentsList: null, variants: null, stock: 50 },
  { id: 43, name: 'Transistor BC547 (10pcs)', price: 15, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51X-oWz+fmL.jpg', icon: 'fa-microchip', desc: 'General purpose NPN bipolar junction transistor for low power switching and amplification.', details: '• Type: NPN Bipolar Junction\n• Model: BC547\n• Max Current: 100mA', componentsList: null, variants: null, stock: 50 },
  { id: 44, name: 'Diode 1N4007 (10pcs)', price: 15, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51r-v6W8hPL.jpg', icon: 'fa-minus', desc: 'Standard 1A power rectifier diode for reverse polarity protection and AC to DC conversion.', details: '• Model: 1N4007\n• Max Reverse Voltage: 1000V\n• Forward Current: 1A', componentsList: null, variants: null, stock: 50 },
  { id: 45, name: 'Voltage Regulator 7805', price: 20, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51-mK9q5-cL.jpg', icon: 'fa-microchip', desc: 'Robust 5V linear voltage regulator offering thermal overload and short circuit protection.', details: '• Model: LM7805\n• Output Voltage: 5V Fixed\n• Max Current: 1.5A (with heatsink)', componentsList: null, variants: null, stock: 50 },
  { id: 51, name: 'NE555 Timer IC (5pcs)', price: 25, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51P+R4C3tSL.jpg', icon: 'fa-clock', desc: 'Industry standard highly stable precision timing IC capable of producing accurate delays.', details: '• Package: DIP-8\n• Function: Precision Timer/Oscillator\n• Max Frequency: 500 kHz', componentsList: null, variants: null, stock: 50 },
  { id: 24, name: '9V Battery with Clip', price: 20, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61-A7Y+f0rL.jpg', icon: 'fa-battery-full', desc: 'Standard 9V alkaline power cell complete with a pre wired snap on terminal connector.', details: '• Connector: Standard 9V Snap\n• Output Leads: Tinned bare wire\n• Material: Faux leather housing', componentsList: null, variants: null, stock: 50 },
  { id: 25, name: 'Tactile Buttons (10pcs)', price: 10, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61h3N1F8V+L.jpg', icon: 'fa-fingerprint', desc: 'Momentary normally open SPST push button switches for physical user input.', details: '• Type: Momentary SPST\n• Dimensions: 6x6x5mm\n• Mounting: Through-hole PCB', componentsList: null, variants: null, stock: 50 },
  { id: 26, name: 'Joystick Module', price: 45, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51lO+w-xO1L.jpg', icon: 'fa-gamepad', desc: 'Dual axis analog XY joystick module complete with an integrated Z axis tactile switch.', details: '• Interface: Dual Analog (X,Y) + Digital (Z)\n• Operating Voltage: 5V\n• Springs: Auto-centering', componentsList: null, variants: null, stock: 50 },
  { id: 53, name: 'MG995 Metal Servo', price: 250, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51owZmMUTlL.jpg', icon: 'fa-cogs', desc: 'High torque metal geared servo motor delivering exceptional physical durability.', details: '• Torque: 10kg/cm (at 6V)\n• Rotation: 180°\n• Gearing: Full Metal Gearbox', componentsList: null, variants: null, stock: 50 },
  { id: 38, name: 'LM2596 Buck Converter', price: 45, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61gX-P9sVcL.jpg', icon: 'fa-bolt', desc: 'High efficiency DC to DC step down buck converter with an adjustable output potentiometer.', details: '• Topology: Buck (Step-Down)\n• Output Current: 3A (Max)\n• Output Voltage: 1.23V-30V Adjustable', componentsList: null, variants: null, stock: 50 },
  { id: 39, name: 'TP4056 Charger', price: 20, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51Gh3teyGzL.jpg', icon: 'fa-battery-half', desc: 'Linear lithium ion battery charging module featuring constant current constant voltage algorithms.', details: '• Input: Micro-USB / Type-C\n• Charging Current: 1A (Adjustable)\n• Cut-off Voltage: 4.2V ± 1%', componentsList: null, variants: null, stock: 50 },
  { id: 40, name: '18650 Li-ion Battery', price: 50, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61v-O-f3F4L.jpg', icon: 'fa-battery-full', desc: 'Rechargeable high capacity 3.7V lithium ion cylindrical cell for portable power solutions.', details: '• Chemistry: Lithium-Ion\n• Nominal Voltage: 3.7V\n• Form Factor: 18650 Cylindrical', componentsList: null, variants: null, stock: 50 },
  { id: 46, name: 'Potentiometer 10k', price: 15, discount: '35', category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61O+C2O5bHL.jpg', icon: 'fa-sliders-h', desc: 'Precision 10k ohm rotary variable resistor for continuous analog voltage division.', details: '• Resistance: 10k Ohm\n• Type: Rotary Linear Taper\n• Interface: 3-Pin Breadboard Friendly', componentsList: null, variants: null, stock: 50 },
  { id: 300, name: 'MPU6050 Gyro Module', price: 120, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51tE5E+kK1L.jpg', icon: 'fa-compass', desc: '6-DOF Accelerometer and Gyroscope module for orientation and motion tracking.', details: '• Interface: I2C\n• Axes: 3-axis Gyroscope\n• Axes: 3-axis Accelerometer', componentsList: null, variants: null, stock: 50 },
  { id: 301, name: 'NRF24L01 Transceiver', price: 90, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51badOM+-CL.jpg', icon: 'fa-broadcast-tower', desc: '2.4GHz RF transceiver module for ultra long-range wireless communication.', details: '• Frequency: 2.4GHz ISM band\n• Interface: High-speed SPI\n• Range: Ultra long-range line-of-sight', componentsList: null, variants: null, stock: 50 },
  { id: 302, name: 'DS3231 RTC Module', price: 140, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61f4V8P8R+L.jpg', icon: 'fa-clock', desc: 'Highly accurate I2C real-time clock with an integrated temperature compensated crystal.', details: '• Interface: I2C\n• Accuracy: ±2ppm\n• Battery: CR2032 (Included)', componentsList: null, variants: null, stock: 50 },
  { id: 303, name: 'RFID RC522 Module', price: 130, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61WfB3wY9XL.jpg', icon: 'fa-id-card', desc: '13.56MHz contactless smart card reader module equipped with SPI interface.', details: '• Frequency: 13.56MHz\n• Interface: SPI\n• Included: Reader module, blank card, key fob', componentsList: null, variants: null, stock: 50 },
  { id: 304, name: '4x4 Matrix Keypad', price: 50, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51oV7e8Q8tL.jpg', icon: 'fa-calculator', desc: '16-button membrane keypad matrix designed for rapid alphanumeric user input.', details: '• Type: Membrane Matrix\n• Layout: 4x4 (16 buttons)\n• Connection: 8-pin female header', componentsList: null, variants: null, stock: 50 },
  { id: 305, name: 'LDR Photoresistors (10pcs)', price: 30, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61p-R+mG-QL.jpg', icon: 'fa-sun', desc: 'Light-dependent resistors for dynamic ambient light detection and triggering.', details: '• Type: Light Dependent Resistor (LDR)\n• Diameter: 5mm\n• Quantity: 10 pieces', componentsList: null, variants: null, stock: 50 },
  { id: 306, name: 'XL6009 Boost Converter', price: 110, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/61gX-P9sVcL.jpg', icon: 'fa-arrow-up', desc: 'High-performance DC-DC step-up voltage converter module with adjustable output.', details: '• Topology: DC-DC Step-Up (Boost)\n• Input Voltage: 3V - 32V\n• Output Voltage: 5V - 35V (Adjustable)', componentsList: null, variants: null, stock: 50 },
  { id: 307, name: '5V 2A Power Adapter', price: 150, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51-mK9q5-cL.jpg', icon: 'fa-plug', desc: 'Reliable SMPS power supply adapter equipped with a standard 5.5mm DC barrel jack.', details: '• Output: 5V DC @ 2A\n• Connector: 5.5mm x 2.1mm Barrel Jack\n• Topology: Switch Mode Power Supply (SMPS)', componentsList: null, variants: null, stock: 50 },
  { id: 308, name: 'Breadboard Power Supply', price: 70, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51Gh3teyGzL.jpg', icon: 'fa-charging-station', desc: 'MB102 compatible dual-voltage breadboard power module with USB input.', details: '• Compatibility: MB102 Breadboards\n• Input: USB or Barrel Jack\n• Output: 3.3V / 5V (Selectable via jumper)', componentsList: null, variants: null, stock: 50 },
  { id: 309, name: 'Header Pins (10pcs)', price: 40, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/71hO0a2o+6L.jpg', icon: 'fa-grip-lines', desc: 'Breakaway PCB male header pins featuring standard 2.54mm pitch spacing.', details: '• Type: Breakaway Male Headers\n• Pitch: 2.54mm (0.1")\n• Row: Single Row (40 pins each)', componentsList: null, variants: null, stock: 50 },
  { id: 310, name: 'SG3525 PWM IC', price: 25, discount: null, category: 'components', rating: 0, image: 'https://m.media-amazon.com/images/I/51P+R4C3tSL.jpg', icon: 'fa-microchip', desc: 'Pulse width modulator IC specifically designed for switch-mode power supplies.', details: '• Type: Pulse Width Modulator (PWM) Controller\n• Package: DIP-16\n• Application: Inverters & SMPS', componentsList: null, variants: null, stock: 50 },

  // PROJECTS (27)
  { id: 13, name: 'Obstacle Avoidance Bot', price: 800, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: null, desc: 'Autonomous robotic platform engineered for dynamic acoustic collision avoidance.', details: '• Application: Dynamic acoustic collision avoidance\n• Difficulty: Beginner/Intermediate\n• Includes: Full structural chassis & logic board', componentsList: ['Arduino Uno', 'Motor Shield', 'Ultrasonic Sensor', 'Servo', 'Chassis'], variants: null, stock: 50 },
  { id: 14, name: 'Solar Tracker', price: 600, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-traffic-light', desc: 'Dual servo optoelectronic system designed to autonomously track peak light intensity.', details: '• Application: Optoelectronic light tracking\n• Architecture: Dual-servo pan/tilt\n• Includes: Solar cell & LDR array', componentsList: ['Arduino Uno', 'Servos x2', 'LDRs x4', 'Solar Panel'], variants: null, stock: 50 },
  { id: 15, name: 'Distance Alarm', price: 350, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-volume-up', desc: 'Proximity alert system utilizing acoustic range finding and escalating piezoelectric feedback.', details: '• Application: Acoustic proximity alerts\n• Feedback: Escalating tone frequency\n• Core: Microcontroller driven logic', componentsList: ['Arduino Nano', 'Ultrasonic Sensor', 'Buzzer'], variants: null, stock: 50 },
  { id: 27, name: 'Digital Thermometer', price: 400, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-thermometer-half', desc: 'Real time environmental monitoring system featuring an integrated alphanumeric readout.', details: '• Application: Real-time thermal telemetry\n• Display: 16x2 I2C LCD readout\n• Accuracy: High precision calibration', componentsList: ['Arduino Uno', 'Temp Sensor', '16x2 LCD'], variants: null, stock: 50 },
  { id: 28, name: 'Water Level Indicator', price: 250, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-water', desc: 'Transistor based fluid array designed to visually indicate specific liquid volume thresholds.', details: '• Application: Fluid volume monitoring\n• Architecture: Multi-stage transistor gates\n• Feedback: Visual LED array', componentsList: ['Transistors x4', 'Resistors', 'LEDs', 'Buzzer'], variants: null, stock: 50 },
  { id: 29, name: 'Smart Irrigation Kit', price: 650, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-moon', desc: 'IoT enabled agricultural automation unit for maintaining optimal soil moisture levels.', details: '• Application: Automated crop watering\n• Connectivity: WiFi IoT Integration\n• Actuation: High power water pump', componentsList: ['NodeMCU', 'Moisture Sensor', 'Relay', 'Water Pump'], variants: null, stock: 50 },
  { id: 30, name: 'Smart Dustbin', price: 450, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-id-card', desc: 'Automated ultrasonic sanitary disposal system featuring a mechanized lid apparatus.', details: '• Application: Touchless waste management\n• Sensor: HC-SR04 proximity trigger\n• Actuation: 180-degree servo mechanism', componentsList: ['Arduino Nano', 'Ultrasonic Sensor', 'Servo Motor'], variants: null, stock: 50 },
  { id: 31, name: 'Radar System', price: 400, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-id-card', desc: 'Sweeping acoustic sensor array designed to map out spatial data in a 180 degree field.', details: '• Application: 180-degree spatial mapping\n• Interface: Processing/Java visualizer\n• Mechanism: Sweeping servo mount', componentsList: ['Arduino Uno', 'Ultrasonic Sensor', 'Servo'], variants: null, stock: 50 },
  { id: 32, name: 'Custom Project', price: 0, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-id-card', desc: 'Bespoke engineering solutions and tailored hardware architectures available upon request.', details: '• Application: Bespoke hardware architecture\n• Scope: Tailored to client specifications\n• Consultation: Required prior to order', componentsList: ['Contact for details'], variants: null, stock: 50 },
  { id: 100, name: 'Traffic Light System', price: 250, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-traffic-light', desc: 'Sequential automated intersection simulation using timed algorithmic logic.', details: '• Application: Urban transit simulation\n• Logic: Timed sequential loops\n• Difficulty: Beginner friendly', componentsList: ['Arduino Uno', 'LEDs', 'Breadboard'], variants: null, stock: 50 },
  { id: 101, name: 'RFID Door Lock', price: 600, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-lock', desc: 'Secure electromagnetic entry system utilizing encrypted radio frequency identification tags.', details: '• Application: Secure access control\n• Security: 13.56MHz encrypted tags\n• Actuation: Electromagnetic latch simulation', componentsList: ['Arduino Uno', 'RFID Module', 'Servo'], variants: null, stock: 50 },
  { id: 102, name: 'Automated Night Lamp', price: 200, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-lightbulb', desc: 'Autonomous lighting solution triggered by a precisely calibrated photoresistor circuit.', details: '• Application: Ambient light regulation\n• Sensor: Calibrated LDR bridge\n• Actuation: 220V AC relay switching', componentsList: ['Arduino Uno', 'LDR', 'Relay'], variants: null, stock: 50 },
  { id: 103, name: 'Bluetooth Car Kit', price: 1200, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-car-side', desc: 'Remote controlled wireless mobile platform operated via a smartphone application.', details: '• Application: Wireless telemetry transit\n• Protocol: Bluetooth V2.0+EDR\n• Chassis: 4-Wheel/2-Wheel drive', componentsList: ['Arduino Uno', 'Bluetooth Module', 'Chassis'], variants: null, stock: 50 },
  { id: 104, name: 'Digital Clock (RTC)', price: 450, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-clock', desc: 'Highly accurate chronometer utilizing an I2C real time clock module for minimal drift.', details: '• Application: Precision timekeeping\n• Core: DS3231 Temperature Compensated RTC\n• Display: High contrast LCD', componentsList: ['Arduino Uno', 'RTC Module', '16x2 LCD'], variants: null, stock: 50 },
  { id: 105, name: 'Smoke Detector', price: 300, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-fire', desc: 'Early warning environmental hazard array sensitive to volatile gasses and particulate smoke.', details: '• Application: Environmental hazard warning\n• Sensor: Semiconductor gas detector\n• Alert: High decibel piezo buzzer', componentsList: ['Arduino Uno', 'Gas Sensor', 'Buzzer'], variants: null, stock: 50 },
  { id: 106, name: 'Clap Switch', price: 200, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-hands-clapping', desc: 'Acoustically triggered toggling system for hands free control of electrical appliances.', details: '• Application: Acoustic appliance toggling\n• Sensor: Electret condenser mic\n• Actuation: High voltage relay', componentsList: ['Arduino Uno', 'Sound Sensor', 'Relay'], variants: null, stock: 50 },
  { id: 107, name: 'Soil Moisture Alert', price: 250, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-seedling', desc: 'Capacitive moisture detection circuit designed to signal optimal agricultural watering cycles.', details: '• Application: Agricultural telemetry\n• Sensor: Anti-corrosion moisture probe\n• Output: Visual/Audio threshold alerts', componentsList: ['Arduino Uno', 'Moisture Sensor', 'Buzzer'], variants: null, stock: 50 },
  { id: 108, name: 'Laser Security Alarm', price: 250, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-shield-alt', desc: 'Security tripwire perimeter system utilizing a coherent light beam and photoresistor.', details: '• Application: Perimeter breach detection\n• Sensor: Coherent laser beam diode\n• Logic: Interrupt triggered alarm state', componentsList: ['Arduino Uno', 'Laser Diode', 'LDR'], variants: null, stock: 50 },
  { id: 109, name: 'Heart Rate Monitor', price: 450, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-heartbeat', desc: 'Optical biometric diagnostic tool for recording and visualizing human pulse waveforms.', details: '• Application: Biometric health logging\n• Sensor: Optical pulse reader\n• Display: Graphical OLED waveform', componentsList: ['Arduino Uno', 'Pulse Sensor', 'OLED'], variants: null, stock: 50 },
  { id: 110, name: 'Digital Dice', price: 200, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-dice', desc: 'Electronic random number generator outputting visual data via a 7 segment matrix.', details: '• Application: Algorithmic RNG generator\n• Output: 7-Segment numerical display\n• Input: Tactile debounced push button', componentsList: ['Arduino Uno', '7-Segment Display', 'Button'], variants: null, stock: 50 },
  { id: 111, name: 'Alcohol Breathalyzer', price: 450, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-beer', desc: 'Diagnostic analysis unit utilizing a tin dioxide sensor for vapor concentration metrics.', details: '• Application: Vapor concentration metrics\n• Sensor: SnO2 Semiconductor (MQ-3)\n• Output: 16x2 Alphanumeric LCD', componentsList: ['Arduino Uno', 'MQ-3 Sensor', '16x2 LCD'], variants: null, stock: 50 },
  { id: 112, name: 'Smart Fan (Temp Control)', price: 350, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-fan', desc: 'Automated thermal regulation system that adjusts RPM variables based on ambient heat.', details: '• Application: Dynamic thermal regulation\n• Logic: Temperature to PWM conversion\n• Actuation: Variable speed DC motor', componentsList: ['Arduino Uno', 'Temp Sensor', 'Motor'], variants: null, stock: 50 },
  { id: 113, name: 'Piano (Piezo)', price: 200, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-music', desc: 'Miniaturized tactile synthesizer utilizing square waves to replicate musical frequencies.', details: '• Application: Frequency wave synthesis\n• Input: Multi-button tactile array\n• Output: Tone-mapped piezo buzzer', componentsList: ['Arduino Uno', 'Piezo', 'Buttons'], variants: null, stock: 50 },
  { id: 114, name: 'Calculator', price: 450, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-calculator', desc: 'Computational matrix hardware capable of executing and displaying arithmetic logic.', details: '• Application: Arithmetic logic processing\n• Input: 4x4 Membrane Keypad Matrix\n• Display: Real-time LCD equation rendering', componentsList: ['Arduino Uno', 'Keypad', '16x2 LCD'], variants: null, stock: 50 },
  { id: 115, name: 'Line Follower Robot', price: 850, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71z7x0mOQ6L.jpg', icon: 'fa-road', desc: 'Autonomous transit drone utilizing infrared reflectance to navigate designated paths.', details: '• Application: Infrared reflectance navigation\n• Drive Type: Differential 2-wheel drive\n• Includes: IR sensor array & logic board', componentsList: ['Arduino Uno', 'IR Sensors', 'Chassis'], variants: null, stock: 50 },
  { id: 116, name: 'RFID Attendance System', price: 750, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-id-badge', desc: 'Enterprise grade personnel logging system synchronizing RFID tokens with an RTC.', details: '• Application: Personnel database logging\n• Core: RC522 RFID & DS3231 RTC\n• Output: Timestamped ID verification', componentsList: ['Arduino Uno', 'RFID', 'RTC'], variants: null, stock: 50 },
  { id: 118, name: 'Water Quality Tester', price: 550, discount: null, category: 'projects', rating: 0, image: 'https://m.media-amazon.com/images/I/71uP2pQ-g3L.jpg', icon: 'fa-water', desc: 'Fluid diagnostic device for measuring total dissolved solids and electrical conductivity.', details: '• Application: Fluid impurity analysis\n• Sensor: Total Dissolved Solids (TDS) Probe\n• Readout: Real-time OLED display', componentsList: ['Arduino Uno', 'TDS Sensor', 'OLED'], variants: null, stock: 50 },

  // KITS (2)
  { id: 201, name: 'Arduino Starter Kit', price: 900, discount: null, category: 'kits', rating: 0, image: 'https://m.media-amazon.com/images/I/81KJPqDhpKL.jpg', icon: 'fa-box-open', desc: 'Comprehensive developmental foundation kit equipped with core logic and passive components.', details: '• Target Audience: Electronics beginners\n• Core: ATmega328P based development board\n• Components: Breadboard, LEDs, passives, wiring', componentsList: ['Arduino Uno', 'Breadboard', 'Wires', 'LEDs'], variants: null, stock: 50 },
  { id: 202, name: 'Electronics Lab Kit', price: 800, discount: null, category: 'kits', rating: 0, image: 'https://m.media-amazon.com/images/I/51JN1WGrq7L.jpg', icon: 'fa-box-open', desc: 'Essential hardware assembly bundle featuring thermal and diagnostic laboratory equipment.', details: '• Application: Hardware assembly & diagnostics\n• Tools: 60W Thermal Soldering Element\n• Diagnostics: High-accuracy digital multimeter', componentsList: ['Multimeter', 'Soldering Iron', 'Solder'], variants: null, stock: 50 }
];

export async function GET() {
  try {
    let count = 0;
    
    // We loop through the array and push each item to Firebase
    for (const item of inventoryData) {
      // We use your custom integer 'id' as the document name in Firebase
      const documentReference = doc(db, 'inventory', item.id.toString());
      await setDoc(documentReference, item);
      count++;
    }

    return NextResponse.json({ 
      success: true, 
      message: `Successfully injected ${count} products into Firebase!` 
    });

  } catch (error: any) {
    console.error("Firebase Error: ", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}