export interface Product {
  id: number;
  name: string;
  price: number;
  category: string;
  rating: number;
  image: string;
  desc: string;
  details: string;
  // These are now optional (?) to fix the errors
  discount?: string;
  icon?: string;
  componentsList?: string[];
  variants?: string[];
}

export const products: Product[] = [
  // Microcontrollers
  { id: 1, name: "Arduino Uno R3", price: 400, discount: "20", category: "microcontrollers", rating: 4.9, image: "https://imgs.search.brave.com/bKE7jLkAk2IlrSVGq9Gg6v1c9I31StKiFrSeQkWv6Fc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vd3d3LnJ5/dHJvbmljcy5pbi93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMi8x/MS9BcmR1aW5vLXVu/by1yMy1ESVAtY2gz/NDAuanBlZz9yZXNp/emU9NDAwLDQwMCZz/c2w9MQ", icon: "fa-microchip", desc: "The standard board for beginners. ATmega328P based.", details: "Microcontroller: ATmega328P\nOperating Voltage: 5V\nInput Voltage: 7-12V\nDigital I/O Pins: 14" },
  { id: 2, name: "Arduino Nano V3", price: 355, discount: "32", category: "microcontrollers", rating: 4.8, image: "https://imgs.search.brave.com/Y8PwN2dWJFjff96U6ajpxQiJJsRXM4AZdbIb-Yx8eEo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudGNkbi5jb20u/YnIvaW1nL2ltZ19w/cm9kLzY1MDM2MS9w/bGFjYV9uYW5vX3Zf/M18wX3IzX2F0bWVn/YTMyOF9zZW1fY2Fi/b191c2JfY29tcGF0/aXZlbF9wYXJhX2Fy/ZHVpbm9fMTE4M18x/XzIwMjAwODE4MjAz/NjUzLmpwZw", icon: "fa-memory", desc: "Breadboard friendly, small size, Mini-USB.", details: "Microcontroller: ATmega328\nArchitecture: AVR\nFlash Memory: 32 KB\nSRAM: 2 KB" },
  { id: 3, name: "Arduino Mega 2560", price: 999, discount: "25", category: "microcontrollers", rating: 4.9, image: "https://imgs.search.brave.com/kOFYOLt5KE1jwS3P2D85cBLUPQrXqAl3cpHVO3hna7c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aWVu/ZGEuYnJpY29nZWVr/LmNvbS8yODMxLWxh/cmdlX2RlZmF1bHQv/YXJkdWluby1tZWdh/LTI1NjAuanBn", icon: "fa-server", desc: "For complex projects. More I/O pins and memory.", details: "Microcontroller: ATmega2560\nDigital I/O Pins: 54\nAnalog Input Pins: 16\nFlash Memory: 256 KB" },
  { id: 4, name: "ESP8266 NodeMCU", price: 350, discount: "20", category: "microcontrollers", rating: 4.7, image: "https://imgs.search.brave.com/euFy99OXW0EL5jcbsRRJ8OWdFBMgUO_Vq0gJJDHaGao/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZWxlY3Ryb25pY3dp/bmdzLmNvbS9zdG9y/YWdlL1BsYXRmb3Jt/U2VjdGlvbi9Ub3Bp/Y0NvbnRlbnQvMjEx/L2ljb24vRVNQODI2/NiUyMFdpZmkuanBn", icon: "fa-wifi", desc: "WiFi enabled microcontroller for IoT.", details: "Wi-Fi Module: ESP-12E\nUSB-TTL: CP2102\nPower Input: 4.5V ~ 9V\nLogic Level: 3.3V" },
  { id: 16, name: "ESP32 Dev Module", price: 510, discount: "26", category: "microcontrollers", rating: 4.9, image: "https://imgs.search.brave.com/808z1WNwQGOOho82OMO9zMld-Ltf26LRikwB8wmQw3k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9taWNy/b3B5dGhvbi5vcmcv/cmVzb3VyY2VzL21p/Y3JvcHl0aG9uLW1l/ZGlhL2JvYXJkcy9F/U1AzMl9HRU5FUklD/L2VzcDMyX2Rldmtp/dGMuanBn", icon: "fa-broadcast-tower", desc: "Dual core, WiFi + Bluetooth.", details: "Processors: Dual-Core 32-bit LX6\nClock Speed: 240 MHz\nConnectivity: WiFi + Bluetooth\nRAM: 512 KB" },
  { id: 18, name: "Raspberry Pi4 4gb", price: 8000, discount: "10", category: "microcontrollers", rating: 4.7, image: "https://imgs.search.brave.com/caZJL-LDLeUPJ33cVh6UXM9vVMmpsY4OGZsmi9dQKkg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGVw/aWh1dC5jb20vY2Ru/L3Nob3AvcHJvZHVj/dHMvcmFzcGJlcnJ5/LXBpLTQtbW9kZWwt/Yi1yYXNwYmVycnkt/cGktMTQ4NzkxODYw/NTkzMjYuanBnP3Y9/MTY0NjI0NzYxNyZ3/aWR0aD0xMDAw", icon: "fa-usb", desc: "Mini-Computer based on the Broadcom BCM2711.", details: "Processor: Broadcom BCM2711\nDual-band 2.4 GHz and 5 GHz IEEE.\n802.11ac wireless LAN\nBluetooth 5.0 with BLE\nGigabit Ethernet for high-speed networking.\n40-pin GPIO header\nRam: 4GB LPDDR4 SDRAM" },
  { id: 19, name: "ATTiny85 Digispark", price: 390, discount: "30", category: "microcontrollers", rating: 4.5, image: "https://imgs.search.brave.com/yayfP4wy8mhOJ7TaXPvkmaU4U3YMpSO06nOlSkveB_Y/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFneTNkcXQyMUwu/anBn", icon: "fa-bolt", desc: "Tiny, USB-enabled development board.", details: "Flash: 8k\nI/O Pins: 6\nInterface: USB (Software)\nSize: Ultra Small" },
  { id: 17, name: "Raspberry Pi Pico", price: 350, discount: "20", category: "microcontrollers", rating: 4.8, image: "https://imgs.search.brave.com/1vweQa6x-y7_n2G0_7YjR6MM9gOR-eyDQOnBxTJr1Zs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZWxla3Ryb25pay1r/b21wZW5kaXVtLmRl/L3NpdGVzL3Jhc3Bi/ZXJyeS1waS9mb3Rv/cy9yYXNwYmVycnkt/cGktcGljby5qcGc", icon: "fa-microchip", desc: "Low-cost, high-performance microcontroller board.", details: "Chip: RP2040\nCores: Dual-core Arm Cortex M0+\nClock: 133 MHz\nSRAM: 264KB" },
  { id: 54, name: "Raspberry Pi Zero 2 W", price: 2000, discount: "35", category: "microcontrollers", rating: 4.8, image: "https://imgs.search.brave.com/Hid16kzhBT5FiEDKdfY88XR2TYFBQs10AChM4w3nNjA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGVw/aWh1dC5jb20vY2Ru/L3Nob3AvcHJvZHVj/dHMvcmFzcGJlcnJ5/LXBpLXplcm8tMi1y/YXNwYmVycnktcGkt/c2MwNTEwLTMwNTEx/NzMyNzg1MzQ3XzEw/MDB4LmpwZz92PTE2/NDYyMzQ4MzQ", icon: "fa-memory", desc: "A compact, affordable single-board computer.", details: "Processor: Broadcom BCM2710A1.\nRam: 512 MB LPDDR2 SDRAM.\nConnectivity: 2.4 GHz Wi-Fi and Bluetooth-4.2." },

  // Tools
  { id: 60, name: "Soldering Iron set 60W", price: 250, category: "tools", rating: 4.6, image: "https://m.media-amazon.com/images/I/61BZLe4H9oL._SX522_.jpg", desc: "60 Watt soldering iron set for all electronic applictions.", details: "Power: 60W.\nVoltage: 220V AC.\nTip: Pointed Copper.\n All Essential Accessories Included.\nGood quality,Geniune and Sturdy\nIncluded Soldering Stand.\nIncluded Case with Product." },
  { id: 61, name: "Digital Multimeter", price: 350, category: "tools", rating: 4.8, image: "https://imgs.search.brave.com/3P0dcSRGjf__SS6odCOW6m1OA4gOOkzh0B_1xy2YyaY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9kaWdp/dGFsLWNhcGFjaXRh/bmNlLW1ldGVyLXRl/c3Rpbmctb25lLXdo/aXRlLWNhcGFjaXRv/ci1tdWx0aW1ldGVy/LWlzb2xhdGVkLWNo/ZWNraW5nLW1vdG9y/LTIwOTI4ODA5Ny5q/cGc", desc: "DT830D Compact Digital Multimeter.", details: "Measures: Voltage (AC/DC), Current (DC), Resistance\nDisplay: LCD\nProbes: Included\nReliable and Sturdy" },
  { id: 62, name: "Wire Stripper & Cutter", price: 60, discount: "15", category: "tools", rating: 4.7, image: "https://m.media-amazon.com/images/I/61n-YVWT4pL._SX425_.jpg", desc: "Multipurpose wire stripper and cutter tool.", details: "Material: Carbon Steel\nHandle: Insulated Grip\nReliable and Sturdy" },
  { id: 63, name: "Soldering Stand", price: 100, category: "tools", rating: 4.5, image: "https://imgs.search.brave.com/1wOpdeRsjiZHecMZ6dgjuqhxltA_SYuowWl5Y9Ong7E/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjExZklQUWkwdEwu/anBn", desc: "Sturdy stand for holding hot soldering iron.", details: "Material: Metal Spring & Base\nSponge: Included" },
  { id: 64, name: "Desoldering Pump", price: 120, category: "tools", rating: 4.6, image: "https://imgs.search.brave.com/H996tkLLOOaB4HDbXM6GKnIcniJGk4jmCt-AfUAxsrc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zaGFy/dmllbGVjdHJvbmlj/cy5jb20vd3AtY29u/dGVudC91cGxvYWRz/LzIwMjAvMDIvQzVl/LmpwZw", desc: "Suction pump to remove excess solder.", details: "Body: Aluminum/Plastic\nTip: Heat Resistant Teflon" },
  { id: 65, name: "Solder Wire (250g)", price: 90, category: "tools", rating: 4.8, image: "https://imgs.search.brave.com/9Oy0ClbjFXxvuKB5jisH60_q3TkX-IUtUf1nnFI1Gr0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pZWxl/Y3Ryb255LmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMS8w/MS9Tb2xkZXJpbmct/V2lyZS1KYXBhbi0x/LnBuZw", desc: "60/40 Tin Lead Rosin Core Solder Wire.", details: "Weight: 250g\nDiameter: 0.8mm\nFlux Core: Yes" },
  { id: 66, name: "Hot Glue Gun", price: 250, category: "tools", rating: 4.7, image: "https://m.media-amazon.com/images/I/618L6ygDkoL._SX522_.jpg", desc: "Reliable 20W Hot Glue Gun", details: "Power: 100W\nVoltage: 110-240V\nStick Size: 11mm\nGlue sticks included(5pcs)\nReliable and Sturdy" },
  { id: 67, name: "Precision Screwdriver Set", price: 200, category: "tools", rating: 4.6, image: "https://m.media-amazon.com/images/I/71lwyj4rjmL._SX522_.jpg", desc: "27-in-1 Magnetic Screwdriver Toolkit.", details: "Bits: Phillips, Torx, Slotted, Hex\nCase: Included" },
  { id: 68, name: "ESD Tweezer Set", price: 150, category: "tools", rating: 4.7, image: "https://imgs.search.brave.com/8ZbJvni5xZQOh4vyPWvHQPbkSmA6yICNYWjGWW_JNOc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjF4U1JyU2h4bkwu/anBn", desc: "Anti-static tweezers for electronics.", details: "Quantity: 6 pieces\nMaterial: Stainless Steel\nCoating: ESD Safe" },
  { id: 69, name: "Helping Hands", price: 300, category: "tools", rating: 4.5, image: "https://imgs.search.brave.com/S1dl9niVOSTiBnvSwM7LjVgnTI4JrsibS-Y0cONaqSs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFlT2FIdkpYWEwu/anBn", desc: "Soldering stand with magnifier glass.", details: "Arms: 2 Alligator Clips\nMagnifier: 2x Glass Lens\nBase: Heavy Cast Iron" },

  // Components
  { id: 5, name: "Ultrasonic Sensor", price: 80, category: "components", rating: 4.5, image: "https://imgs.search.brave.com/v3bOS_V-ObFLAGcw_KSMiCBjCx6aLaUeWv9NA4Hf_78/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yb2J1/LmluL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE0LzA4L2hjLXNy/MDRfdWx0cmFzb25p/Y19zZW5zb3JfZGlz/dGFuY2VfbWVhc3Vy/aW5nX21vZHVsZV8x/Xy0zMTR4MjUyLmpw/Zw", icon: "fa-satellite-dish", desc: "HC-SR04 for distance measurement.", details: "Range: 2cm to 400cm\nAccuracy: 3mm\nOperating Voltage: 5V" },
  { id: 6, name: "Servo Motor SG90", price: 90, category: "components", rating: 4.6, image: "https://imgs.search.brave.com/ZEa83i8tshyu4bZN3oPECKFHDgcsDJgk-7JVrmQrNWE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yb2Jv/bWFuLmluL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIyLzA5LzEx/MS5qcGc", icon: "fa-cogs", desc: "180 degree rotation micro servo.", details: "Torque: 1.8 kgf·cm\nSpeed: 0.1 s/60 degree\nWeight: 9g" },
  { id: 7, name: "Jumper Wires (10pcs)", price: 70, discount: "25", category: "components", rating: 4.8, image: "https://imgs.search.brave.com/KyTb0J_1qqcJFx404zgoVEVXuAOElR1sxwvPisiYS-I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pZWxl/Y3Ryb255LmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMS8x/MC9JTUctMjAyMTEw/MDctV0EwMDAwLmpw/Zw", icon: "fa-random", desc: "Flexible wires. Select Type.", details: "Length: 20cm\nQuantity: 10 wires/strip", variants: ["Male-to-Male", "Male-to-Female", "Female-to-Female"] },
  { id: 8, name: "IR Sensor Module", price: 70, discount: "35", category: "components", rating: 4.4, image: "https://imgs.search.brave.com/qRzQ28l7vp3rqskpqtELCCS3j_Yi1SQBGVFX3KbcMpY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFLSU41Wjd5Nkwu/anBn", icon: "fa-eye", desc: "Infrared obstacle detection sensor.", details: "Detection Distance: 2-30cm\nOutput: Digital (0/1)\nIndicator: Power & Status LED" },
  { id: 9, name: "Relay Module 1-CH", price: 75, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/HOAt5PsnvxEow_gv_yNhbNKoHg2sTV4XlnWd1LXNfuA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFZdUxCOUdidUwu/anBn", icon: "fa-toggle-on", desc: "Single channel relay for controlling AC/DC loads.", details: "Channel: 1\nLoad: 250V AC / 10A\nTrigger Current: 5mA" },
  { id: 47, name: "Relay Module 4-CH", price: 225, discount: "30", category: "components", rating: 4.8, image: "https://imgs.search.brave.com/HO4l8fEZ0L7lZR__dUPIepCiQ2PLimLJwyOUZHLDcd0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vYWUwMS5h/bGljZG4uY29tL2tm/L0gwMjViZmI2ZDM1/ZmQ0Nzk4YWQ5NDU4/Njc1MzQwNjBiMzMv/MXBjcy1sb3QtNC1j/aGFubmVsLXJlbGF5/LW1vZHVsZS00LWNo/YW5uZWwtcmVsYXkt/Y29udHJvbC1ib2Fy/ZC13aXRoLW9wdG9j/b3VwbGVyLVJlbGF5/LU91dHB1dC00Lmpw/Zz9jcm9wPTMsNCw5/NTgsNjE0JnF1YWxp/dHk9MzEzNg", icon: "fa-server", desc: "4 Channel 5V Relay module.", details: "Channels: 4\nOptocoupler Isolation: Yes\nLoad: 10A 250VAC" },
  { id: 10, name: "L293D Motor Driver", price: 215, discount: "15", category: "components", rating: 4.8, image: "https://imgs.search.brave.com/UAiJt-hUk3TbAslIMRZY7Pm71zoK4uHxlE7LP1n0Yrk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFySVZnQzE5Ykwu/anBn", icon: "fa-car-battery", desc: "Control speed and direction of two DC motors.", details: "Chip: L293D\nDrive Voltage: 5-35V\nMax Current: 600mA/channel" },
  { id: 33, name: "Dc motor with Wheel", price: 120, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/3Z9TlxhpumZ3fg02_P8ntVpbjh9cK-bz-CaPc7ql9pA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFUNU1VdGxMNUwu/anBn", icon: "fa-car", desc: "Motor with wheel for Car Projects.", details: "Type: TT motor\nVoltage: 3V–6V DC\nMax Speed: 200RPM" },
  { id: 34, name: "3.7V Dc Pump with Tube", price: 120, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/p7J9UGtvQ1DoyvZdG0jFvSSi4a_3Yktop7FjjQZ9sU4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudGhpbmdiaXRz/Lm5ldC9leUppZFdO/clpYUWlPaUowYUds/dVoySnBkSE10Ym1W/MElpd2lhMlY1SWpv/aVkzUjJiM055YmpK/c2FtNHdkemx2ZDNV/NWFtSXllV05rY0hn/NWNpSXNJbVZrYVhS/eklqcDdJbkpsYzJs/NlpTSTZleUozYVdS/MGFDSTZPVGN3TENK/b1pXbG5hSFFpT2pj/eU9Dd2labWwwSWpv/aVkyOTJaWElpZlgx/OQ", icon: "fa-car", desc: "Low power motor for water pumping.", details: "Flow Rate (L/Hr):	80 to 120 \nVoltage Rating (V):3-6V Dc \nMax Current: 0.22A" },
  { id: 35, name: "L298N Motor Driver", price: 220, discount: "25", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/R5rum7SY1gmFdtRfFEhK59ah1DiOT5IamzftQmdizYw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFxMytIRE54M0wu/anBn", icon: "fa-car", desc: "High power dual motor driver module.", details: "Chip: L298N\nVoltage: 5-35V\nMax Current: 2A/channel\nHeatsink: Included" },
  { id: 36, name: "MQ-3 Alcohol Sensor", price: 120, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/Hmjl6C9MrEGnDWLujNMSBkhA4fCY8lx637zoJ3Ez5Yk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFPVlVjUXV3S0wu/anBn", icon: "fa-car", desc: "For alcohol Breath Detection.", details: "Detection Limit: 0.04 mg/L-4 mg/L\nVoltage: 5V DC\nPreheat Time: 24hrs (atleast)" },
  { id: 11, name: "LCD Display 16x2", price: 180, discount: "15", category: "components", rating: 4.6, image: "https://imgs.search.brave.com/_wQohce-Irz1E8JqYwXME2MRl4NcBBirpxviT6Xvh34/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFMbFpYQnVnY0wu/anBn", icon: "fa-tv", desc: "Green backlight alphanumeric display.", details: "Format: 16 chars x 2 lines\nBacklight: Green\nController: HD44780" },
  { id: 52, name: "OLED Display 0.96\"", price: 230, discount: "20", category: "components", rating: 4.9, image: "https://imgs.search.brave.com/nV_5RXGEer-aQXDQOW1BkYwtlpIUrHsT7nYFuURBA7A/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFPSllycUJzUUwu/anBn", icon: "fa-tv", desc: "I2C 128x64 Blue/White OLED Display.", details: "Resolution: 128x64\nInterface: I2C (SDA, SCL)\nDriver: SSD1306\nVoltage: 3.3V-5V" },
  { id: 12, name: "Bluetooth HC-05", price: 300, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/iDwDj3Y9NfLO_YX1Wmp2AyHBt0qVa3AklzefpHXHAyQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzA1/NTkvMTk3MC82MjY1/L2ZpbGVzL0Jsb2df/RmVhdHVyZWRfSW1h/Z2VzXzIucG5nP3Y9/MTczNDYwNjYwOA", icon: "fa-bluetooth", desc: "Wireless serial communication module.", details: "Protocol: Bluetooth v2.0+EDR\nRange: 10m\nMode: Master/Slave" },
  { id: 20, name: "DHT11 Sensor", price: 60, discount: "35", category: "components", rating: 4.3, image: "https://imgs.search.brave.com/kigkkPRo1x9yQsUDXdKGjbNdIT2AVKP5J9CKR0oDekM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbGVj/dHJvaHViLWVnLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/NC8wNy9LWS0wMTUt/YW5kLURIVDExLVRl/bXBlcmF0dXJlLWFu/ZC1IdW1pZHR5LVNl/bnNvci0wMy00MDB4/Mjg0LTEuanBn", icon: "fa-temperature-high", desc: "Basic temperature and humidity sensor.", details: "Temp Range: 0-50°C\nHumidity Range: 20-90%\nAccuracy: ±2°C" },
  { id: 37, name: "PIR Motion Sensor", price: 60, discount: "35", category: "components", rating: 4.5, image: "https://imgs.search.brave.com/KzhQ6yH-tGagzIzmqjgDLbG2NXpMS_u0_3xBQI8S5rs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Zmx5cm9iby5pbi9p/bWFnZS9jYWNoZS93/cC9nai9waXItbW90/aW9uLWRldGVjdG9y/LXNlbnNvci1tb2R1/bGUvcGlyLXNlbnNv/ci0zLTU1MHg1NTAu/d2VicA", icon: "fa-walking", desc: "HC-SR501 Body Motion Sensor.", details: "Type: Passive Infrared\nDelay Time: Adjustable\nRange: Adjustable (3-7m)" },
  { id: 48, name: "Piezo Buzzer", price: 30, discount: "35", category: "components", rating: 4.2, image: "https://imgs.search.brave.com/MVt0VwO9J0RkofRLGA-0ysYr5AwN4uJ6KppztRIVeWk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yb2Jv/Y3JhemUuY29tL2Nk/bi9zaG9wL2ZpbGVz/LzFfUGllem9fQnV6/emVyX0JpZ182LTEy/Vl8zODliM2ExMS03/ZWQ5LTQ3MmUtYmY0/ZC1iYTk0MjJkYTE1/OWFfbWVkaXVtLnBu/Zz92PTE3NTIyMTA4/ODM", icon: "fa-volume-up", desc: "5V Active Buzzer for alarms.", details: "Voltage: 5V DC\nType: Active (Self-oscillating)" },
  { id: 49, name: "Rain Sensor", price: 70, discount: "35", category: "components", rating: 4.4, image: "https://imgs.search.brave.com/zHtB9xRea1JSMuvoWwyA3iF7w8XpUmwiqjjCX9xgevY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWM1LmFiYy1yYy5w/bC9ocGVjaWFpL2Ux/ZDVjMDdmMzNiM2Ix/NDAyYTdjZDFkNDFm/NmY4M2M3L2VuZ19w/bV9GQy0zNy1yYWlu/LXNlbnNvci13YXRl/ci1kZXRlY3Rvci1m/b3ItQXJkdWluby0z/LTVWLTYzMDhfNC5q/cGc", icon: "fa-cloud-rain", desc: "Raindrops detection module.", details: "Output: Digital (DO) & Analog (AO)\nPotentiometer: Sensitivity adjust" },
  { id: 50, name: "Sound Sensor", price: 50, discount: "35", category: "components", rating: 4.3, image: "https://imgs.search.brave.com/XPx3xYwKhTjigyV6wr2tU-LmRPQUtovExbKqQTQWM7Y/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Zmx5cm9iby5pbi9p/bWFnZS9jYWNoZS93/cC9nai9wcm9kdWN0/L3Byb2R1Y3QtNjQv/My1taW4tNTUweDU1/MC53ZWJw", icon: "fa-microphone", desc: "Microphone sound detection module.", details: "Chip: LM393\nOutput: Digital\nUsage: Clap switch, noise alarm" },
  { id: 21, name: "Breadboard 830", price: 90, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/-MrE2o9P-H9hmss6DG0HueU9LpQmm5ZVBCpN5QGpmbI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aG5oY2FydC5jb20v/Y2RuL3Nob3AvcHJv/ZHVjdHMvQnJlYWRi/b2FyZDJfODAweC5q/cGc_dj0xNjM0ODEy/NjQx", icon: "fa-border-all", desc: "Solderless prototype board with 830 tie-points.", details: "Points: 830\nType: MB-102\nAdhesive Back: Yes" },
  { id: 22, name: "LED Pack (30pcs)", price: 65, discount: "35", category: "components", rating: 4.5, image: "https://imgs.search.brave.com/S4pm2fnIxQ-xOu_DfHSlqNebDMxzLcYZwVn3mzxtmZY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yb2J1/LmluL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE5LzExLzEwMHBj/cy01bW0tTGlnaHQt/QXNzb3J0ZWQtS2l0/LTEuanBn", icon: "fa-lightbulb", desc: "Assorted Red, Green, and Yellow LEDs.", details: "Size: 5mm\nColors: Red, Green, Yellow (10 each)\nQuantity: 30 Pieces" },
  { id: 23, name: "Resistor Kit", price: 100, discount: "35", category: "components", rating: 4.6, image: "https://imgs.search.brave.com/4vYk-GLHPxcFllDspoo-yplOYO-rJrBmzhGFYZtFcgQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFhZWRLSlhJVkwu/anBn", icon: "fa-grip-lines", desc: "Assorted values from 10 ohm to 1M ohm.", details: "Wattage: 1/4W\nType: Carbon Film\nValues: 30 diff values x 10 pcs" },
  { id: 41, name: "Ceramic Capacitors", price: 50, discount: "35", category: "components", rating: 4.4, image: "https://imgs.search.brave.com/-r3_3MmtTkzH_t3_Ar3kFJysltn2PbYc2svThAaWuPM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c21jb21wb25lbnRz/LmNvbS5hdS9jZG4v/c2hvcC9wcm9kdWN0/cy81N180OWMxZmI0/Mi1kMjNkLTRhOTIt/ODI1My0wZWE4MmEw/MWU4N2EuanBnP3Y9/MTY3NTk1MTQyNiZ3/aWR0aD01MzM", icon: "fa-microchip", desc: "Assorted Ceramic Capacitors (pack).", details: "Voltage: 50V\nValues: 10pf to 100nf mixed" },
  { id: 42, name: "Electrolytic Capacitors", price: 80, discount: "35", category: "components", rating: 4.5, image: "https://imgs.search.brave.com/LIfoDGNQ7-9Ktu1QR7OwV8obMZczDd7PScOUxjAD0sw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFwMTFQLUUya0wu/anBn", icon: "fa-battery-quarter", desc: "Assorted Electrolytic Capacitors.", details: "Values: 10uf, 100uf, 470uf, 1000uf mixed\nVoltage: 16V-25V" },
  { id: 43, name: "Transistor BC547", price: 40, discount: "35", category: "components", rating: 4.6, image: "https://imgs.search.brave.com/8mCn2tgK1kvcrhygDtLPGoSeocrNp9j9yWP5z0Ppv_Q/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/Xzc4NTY0MS1NTEI0/NzI0MzExMzY0NF8w/ODIwMjEtRS53ZWJw", icon: "fa-microchip", desc: "NPN General Purpose Transistor (Pack of 10).", details: "Type: NPN\nModel: BC547\nPackage: TO-92" },
  { id: 44, name: "Diode 1N4007", price: 30, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/Dp1dyq5zLJIljyOUtz2-ChuS0zWFFH8OD4Iu9ouz8R0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFRNlI3ZkhONkwu/anBn", icon: "fa-minus", desc: "Rectifier Diode 1A (Pack of 10).", details: "Model: 1N4007\nVoltage: 1000V\nCurrent: 1A" },
  { id: 45, name: "Voltage Regulator 7805", price: 50, discount: "35", category: "components", rating: 4.8, image: "https://imgs.search.brave.com/OSGV1ul6r0A6AlBxDnvE6_caTe5IvIP7-I4H5XzWieI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFoOGtVS0xaZ0wu/anBn", icon: "fa-microchip", desc: "5V Linear Voltage Regulator (Pack of 5).", details: "Output: 5V Fixed\nCurrent: 1.5A Max\nPackage: TO-220" },
  { id: 51, name: "NE555 Timer IC", price: 40, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/7k8zvg662GE6abLeXfbX68aLLO3wTr1V7G9vNlFw1fs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbnZp/c3RpYW1hbGwuY29t/L2Nkbi9zaG9wL3By/b2R1Y3RzL25lNTU1/cC1uZTU1NS1kaXAt/OC10aS1oaWdoLXBy/ZWNpc2lvbi1vc2Np/bGxhdG9yLXRpbWVy/LWljLTU1NS0xMDIw/NTAtcGNzLTQ1MzU1/My5qcGc_dj0xNjYy/NzM1NjcwJndpZHRo/PTE5NDY", icon: "fa-clock", desc: "Precision Timer IC (Pack of 5).", details: "Type: Precision Timer\nPackage: DIP-8\nVoltage: 4.5V - 16V" },
  { id: 24, name: "9V Battery with Clip", price: 25, discount: "35", category: "components", rating: 4.2, image: "https://imgs.search.brave.com/KkPKX-rGeMqaZvSH7YgSt92vR1WabfTSzqgQ5eWelFY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjE4bGx3QmxqRkwu/anBn", icon: "fa-battery-full", desc: "Snap-on with 9V battery (non-rechargable).", details: "Voltage: 9V Dc\nCable: DC Wire Clip" },
  { id: 25, name: "Tactile Buttons", price: 30, discount: "35", category: "components", rating: 4.4, image: "https://imgs.search.brave.com/5eg1v5pA9c9QJvnNNT0dsn6EPF3w2Rbh21tQ2e88ebc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4t/c2hvcC5hZGFmcnVp/dC5jb20vOTcweDcy/OC8xMTE5LTA1Lmpw/Zw", icon: "fa-fingerprint", desc: "10pcs momentary push buttons.", details: "Size: 6x6x5mm\nType: Momentary\nQuantity: 10 Pieces" },
  { id: 26, name: "Joystick Module", price: 60, discount: "35", category: "components", rating: 4.6, image: "https://imgs.search.brave.com/y2xNP1V3SHRcG9o0PJhKziF6nbTZLpu2k7TJOQVSoDQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hcmR1/aW5vbW9kdWxlcy5p/bmZvL3dwLWNvbnRl/bnQvdXBsb2Fkcy9L/WS0wMjNfZHVhbF9h/eGlzX2pveXN0aWNr/X21vZHVsZV9hcmR1/aW5vLTI0MHgyNDAu/anBn", icon: "fa-gamepad", desc: "Dual-axis XY joystick module.", details: "Axes: X, Y + Switch\nOutput: Analog\nVoltage: 5V" },
  { id: 53, name: "MG995 Metal Servo", price: 350, discount: "35", category: "components", rating: 4.8, image: "https://imgs.search.brave.com/UtfQx-Qc-jAlxcVEHVHOst-z8BvZbQbb-GLDvkVERyg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFvd1ptTVRUbEwu/anBn", icon: "fa-cogs", desc: "High torque metal gear servo motor.", details: "Torque: 10kg/cm\nGears: Metal\nRotation: 180 degrees" },
  { id: 38, name: "LM2596 Buck Converter", price: 90, discount: "35", category: "components", rating: 4.7, image: "https://imgs.search.brave.com/JybohW7HKQP2N0yJLAFuduTd5p5tVf1zq_4AcBEVbB4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzE5M1VONTNKcUwu/anBn", icon: "fa-bolt", desc: "DC-DC Step down adjustable power module.", details: "Input: 3V-40V\nOutput: 1.5V-35V (Adjustable)\nCurrent: 3A Max" },
  { id: 39, name: "TP4056 Charger", price: 35, discount: "35", category: "components", rating: 4.6, image: "https://imgs.search.brave.com/VuM6a4jVY1ZKm9QZDSgprk6fbdtSWsBk66IzMWL55KQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFHaDN0ZXlHekwu/anBn", icon: "fa-battery-half", desc: "1A Li-ion battery charging module.", details: "Chip: TP4056\nInput: Micro USB / Type C\nOutput: 4.2V 1A" },
  { id: 40, name: "18650 Li-ion Battery Pack", price: 90, discount: "35", category: "components", rating: 4.5, image: "https://imgs.search.brave.com/oPw7aQZ05Zr9_RYie3SfxOJBushYNaQ4cKpr9p0QTX0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c2t5bmV0cm9ib3Rp/Y3MuaW4vY2RuL3No/b3AvZmlsZXMvbGxs/LmpwZz92PTE3MzE2/MTM3NDImd2lkdGg9/MTQ0NQ", icon: "fa-battery-full", desc: "3.7V Rechargeable Battery 2200mAh with holder.", details: "Voltage: 3.7V\nCapacity: 1200-2200mAh (pack of 2)\nType: Li-ion" },
  { id: 46, name: "Potentiometer 10k", price: 50, discount: "35", category: "components", rating: 4.5, image: "https://imgs.search.brave.com/XFipCRbFcVMaTU-uWxt18po7I10bn_VRKwsnx8RFetg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zaGFy/dmllbGVjdHJvbmlj/cy5jb20vd3AtY29u/dGVudC91cGxvYWRz/LzIwMjEvMDEvMTBL/LU9obS0zUGluLTE1/bW0tU2hhZnQtUG90/ZW50aW9tZXRlci1z/aGFydmllbGVjdHJv/bmljcy0xLTYwMHg2/MDAuanBn", icon: "fa-sliders-h", desc: "10k Ohm Variable Resistor (Pack of 5).", details: "Value: 10k Ohm\nType: Linear Rotary\nKnob: Included" },

  // Simple Projects
  { id: 13, name: "Obstacle Avoidance Bot", price: 2000, category: "projects", rating: 4.7, image: "https://imgs.search.brave.com/bggo56fMJlZBP3VyhC_gN7_au8FlRRVoTy2EA7licLc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50Lmluc3RydWN0/YWJsZXMuY29tL0ZC/QS9NWkVNL0pCUVU0/SFRVL0ZCQU1aRU1K/QlFVNEhUVS5qcGc_/YXV0bz13ZWJwJmZp/dD1ib3VuZHMmZnJh/bWU9MSZoZWlnaHQ9/MTAyNCZ3aWR0aD0x/MDI0YXV0bz13ZWJw/JmZyYW1lPTEmaGVp/Z2h0PTMwMA", desc: "Simple robot that detects walls and turns.", componentsList: ["Arduino Uno", "Motor Driver Shield", "Ultrasonic Sensor", "Servo Motor", "Chassis Kit", "Geared Motors x2", "Wheels x2", "Batteries"], details: "Complete kit for building an obstacle avoidance robot." },
  { id: 14, name: "Sun Tracking Solar Panel", price: 1200, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/ImbWodJ_6j5juaxjYNWPJKDwpeaExq_f3LKyW-DSpeg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/c3Rlci5pbWdpeC5u/ZXQvdXBsb2Fkcy9h/dHRhY2htZW50cy8x/MzM2NjkyL19ZYVRV/bVpxSHZVLmJsb2I_/YXV0bz1jb21wcmVz/cyxmb3JtYXQmdz00/MDAmaD0zMDAmZml0/PW1pbg", icon: "fa-traffic-light", desc: "Using sensors like LDRs to track sunlight.", componentsList: ["Arduino Uno", "Servo Motors x2", "LDR Sensors x4", "Solar Panel (Small)", "Resistors", "Jumper Wires", "Mounting Bracket"], details: "Solar tracker project kit." },
  { id: 15, name: "Distance Alarm", price: 800, category: "projects", rating: 4.6, image: "https://imgs.search.brave.com/J9Aq1qceEqOSvt0jeR05uWC2hXUdlZZGIRiK5UO68c0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50Lmluc3RydWN0/YWJsZXMuY29tL0Y1/VC8xOUtOL0tZTVpL/Q0dCL0Y1VDE5S05L/WU1aS0NHQi5qcGc_/YXV0bz13ZWJwJmZp/dD1ib3VuZHMmZnJh/bWU9MSZoZWlnaHQ9/MTAyNCZ3aWR0aD0x/MDI0YXV0bz13ZWJw/JmZyYW1lPTEmaGVp/Z2h0PTMwMA", icon: "fa-volume-up", desc: "Beeps faster as object gets closer.", componentsList: ["Arduino Nano", "Ultrasonic Sensor HC-SR04", "Buzzer", "Breadboard", "Jumper Wires", "9V Battery Clip"], details: "Distance measuring alarm kit." },
  { id: 27, name: "Digital Thermometer", price: 875, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/hZQf2B_MtzTIInx7I-i5H5ttuzlFd84-PHKOIUfdScw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50Lmluc3RydWN0/YWJsZXMuY29tL0Y3/US9GSEVIL0dVOFM2/RlhKL0Y3UUZIRUhH/VThTNkZYSi5qcGc_/YXV0bz13ZWJwJmZp/dD1ib3VuZHMmZnJh/bWU9MSZoZWlnaHQ9/MTAyNCZ3aWR0aD0x/MDI0YXV0bz13ZWJw/JmZyYW1lPTEmaGVp/Z2h0PTMwMA", icon: "fa-thermometer-half", desc: "Displays temperature on an LCD screen.", componentsList: ["Arduino Uno", "LM35/DHT11 Sensor", "16x2 LCD Display", "Potentiometer (10k)", "Breadboard", "Jumper Wires"], details: "Digital thermometer project kit." },
  { id: 28, name: "Water Level Indicator", price: 700, category: "projects", rating: 4.4, image: "https://imgs.search.brave.com/I-lxDt4k-pNZBxdbhfx_g-hPPzPom12udSQtGUNDjKg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jaXJj/dWl0ZGlnZXN0LmNv/bS9zaXRlcy9kZWZh/dWx0L2ZpbGVzL2lu/bGluZWltYWdlcy91/NS93YXRlci1sZXZl/bC1zZW5zb3ItYXNz/ZW1ibGVkLWltYWdl/LmpwZw", icon: "fa-water", desc: "LED indicators for tank water levels.", componentsList: ["Transistors (BC547) x4", "Resistors", "LEDs (Red, Yellow, Green)", "Buzzer", "PCB/Breadboard", "Battery Clip"], details: "Water level indicator kit." },
  { id: 29, name: "Smart Irrigation Kit", price: 1300, category: "projects", rating: 4.6, image: "https://imgs.search.brave.com/Lwsdp49Tq267h_ewIN4BNaJSQR_m-VnhPN9bps0z0es/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZWNo/YXRyb25pYy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjAv/MDIvSU1HXzIwMjAw/NDE1XzExNTMzNC04/MDB4NjAwLmpwZw", icon: "fa-moon", desc: "Monitor moisture and supply water automatically via WiFi.", componentsList: ["NodeMCU ESP8266", "Soil Moisture Sensor", "Relay Module", "Water Pump", "Tubing", "Jumper Wires"], details: "Smart plant irrigation system." },
  { id: 30, name: "Smart Dustbin", price: 900, category: "projects", rating: 4.8, image: "https://imgs.search.brave.com/CE4XnrUJA2wZsto5PKoO0XleMTynlkEf1Kexs-xUGIg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/a2l0a3JhZnQuaW4v/Y2RuL3Nob3AvZmls/ZXMvcHJvZHVjdF9p/bWFnZS5wbmc_Y3Jv/cD1jZW50ZXImaGVp/Z2h0PTUwMCZ2PTE3/NTEyMDE3ODImd2lk/dGg9NDU0", icon: "fa-id-card", desc: "Smart way to dispose waste.", componentsList: ["Arduino Nano", "Ultrasonic Sensor", "Servo Motor", "Dustbin Chassis", "Battery Holder", "Switch"], details: "Automatic open/close dustbin kit." },
  { id: 31, name: "Radar System", price: 750, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/OiSMGyIjONuthcrPoYQeecf1ejM6Ccwq-Ldc4Ky_A80/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50Lmluc3RydWN0/YWJsZXMuY29tL0ZS/Ui8zWlJKL002N1da/SlVWL0ZSUjNaUkpN/NjdXWkpVVi5qcGc_/YXV0bz13ZWJwJmZp/dD1ib3VuZHMmZnJh/bWU9MSZoZWlnaHQ9/MTAyNCZ3aWR0aD0x/MDI0YXV0bz13ZWJw/JmZyYW1lPTEmaGVp/Z2h0PTMwMA", icon: "fa-id-card", desc: "Radar for detecting foreign elements.", componentsList: ["Arduino Uno", "Ultrasonic Sensor", "Servo Motor", "Processing IDE Code", "Jumper Wires", "Mounting Base"], details: "Radar simulation project." },
  { id: 32, name: "Custom Project", price: 0, category: "projects", rating: 4.8, image: "https://imgs.search.brave.com/Vg0SlD5ax-G1hTu5gvX_ZIsB9HEeLrcRVl-HWg5xs6Q/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTMy/OTc4OTEzOC92ZWN0/b3Ivd3JlbmNoLWlu/c2lkZS10aGUtZ2Vh/ci1sb2dvLmpwZz9z/PTYxMng2MTImdz0w/Jms9MjAmYz1iTUlj/LWtfZHBFRnB1Q3Fx/NjVKcmZxb0VQWVhf/LUY2WTFCN2dyOGd3/TWlrPQ", icon: "fa-id-card", desc: "Any Custom Project.", componentsList: ["Contact us for details"], details: "Contact us for custom requirements." },
  { id: 100, name: "Traffic Light System", price: 450, category: "projects", rating: 4.7, image: "https://imgs.search.brave.com/DUKR8a8OAJPL08IOvMCDrbelRZOXOApQBO2y3TjJfoE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9vc295/b28uY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE3LzA4L1RS/QUZGSUMtTElHSFQu/Z2lm.gif", icon: "fa-traffic-light", desc: "Simulate a traffic intersection with timing.", componentsList: ["Arduino Uno", "Red LED", "Yellow LED", "Green LED", "Resistors", "Breadboard", "Jumper Wires"], details: "Traffic light simulation kit." },
  { id: 101, name: "RFID Door Lock", price: 1200, category: "projects", rating: 4.8, image: "https://imgs.search.brave.com/A7ojApVyJKP9rrgVzrzBQKlIsHPmIaQJuz2qAwh4mN8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/ZmluYWxseS1idWls/dC1teS1vd24tcmZp/ZC1kb29yLWxvY2st/bWVjaGFuaXNtLWFy/ZHVpbm8tcjQtdjAt/MnU4MHpyZ2V5OWJm/MS5qcGc_d2lkdGg9/NjQwJmNyb3A9c21h/cnQmYXV0bz13ZWJw/JnM9ZWE4YmE4MTEx/MTAyOWEwNDNiN2E1/ZDJhNjU2YTA4MzY2/NWZkMzJhMQ", icon: "fa-lock", desc: "Secure entry system using key tags.", componentsList: ["Arduino Uno", "RC522 RFID Module", "Servo Motor SG90", "16x2 LCD", "RFID Tags", "Breadboard", "Wires"], details: "RFID security system project." },
  { id: 102, name: "Automated Night Lamp", price: 350, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/x7nliyHSXuWUWSIkRiyPzG8ikDptukJDITY2ethYJQM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/c3Rlci5pbWdpeC5u/ZXQvdXBsb2Fkcy9h/dHRhY2htZW50cy8x/ODk0MDUyL19xdjZH/TzBGVTFlLmJsb2I_/YXV0bz1jb21wcmVz/cyxmb3JtYXQmdz00/MDAmaD0zMDAmZml0/PW1pbg", icon: "fa-lightbulb", desc: "Turns ON when it gets dark.", componentsList: ["Arduino Uno", "LDR Sensor", "Relay Module", "Bulb Holder", "Resistors", "Wires"], details: "LDR based night lamp." },
  { id: 103, name: "Bluetooth Car Kit", price: 2500, category: "projects", rating: 4.9, image: "https://imgs.search.brave.com/A9WX4JuKXrofeoG3zl7Xxn38TAeaVR79351_hY6qwkg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9vbWFy/dHJvbmljcy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjQv/MDcvSU1HXzEzMjEt/MS1TbWFsbC5qcGc", icon: "fa-car-side", desc: "Control a robot car via smartphone app.", componentsList: ["Arduino Uno", "L298N Driver", "HC-05 Bluetooth", "Chassis", "BO Motors x2", "Wheels", "Battery"], details: "Bluetooth controlled car project." },
  { id: 104, name: "Digital Clock (RTC)", price: 950, category: "projects", rating: 4.6, image: "https://imgs.search.brave.com/2jugXipwPfoO1qaV6AhsAeaufLPTVnlAa3xF2LDr4gA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jaXJj/dWl0ZGlhZ3JhbXMu/aW4vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjEvMDcvQXJkdWlu/b0RpZ2l0YWxDbG9j/ay0xMDI0eDU3Ni5q/cGc", icon: "fa-clock", desc: "Accurate real-time clock with display.", componentsList: ["Arduino Uno", "DS3231 RTC Module", "16x2 LCD with I2C", "Breadboard", "Wires"], details: "Real time clock project." },
  { id: 105, name: "Smoke Detector", price: 600, category: "projects", rating: 4.7, image: "https://imgs.search.brave.com/njLbSzTV6PrauKJHZZhKPeZ5YrlqkjMOogT-YN9J4xY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/c3Rlci5pbWdpeC5u/ZXQvdXBsb2Fkcy9h/dHRhY2htZW50cy8x/MTk2MzQyL19mU2FE/STI1anhaLmJsb2I_/YXV0bz1jb21wcmVz/cyxmb3JtYXQmdz05/MDAmaD02NzUmZml0/PW1pbg", icon: "fa-fire", desc: "Alarm triggers when smoke/gas is detected.", componentsList: ["Arduino Uno", "MQ-2 Gas Sensor", "Buzzer", "Red LED", "Breadboard", "Wires"], details: "Gas leak and smoke detector." },
  { id: 106, name: "Clap Switch", price: 400, category: "projects", rating: 4.4, image: "https://imgs.search.brave.com/LUBD0Y14WJKish-3WyQfEOapmZiar3umxZ4zaRjmQe4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wY2J3/YXlmaWxlLnMzLnVz/LXdlc3QtMi5hbWF6/b25hd3MuY29tL3By/b2plY3QvMjUvMDEv/MjkvMTUwNTQ4NzY0/MmRjODQyZWE1NDQ4/NDBiYmFjYzBmNWI0/YTU1MTBiZmMxNjY4/LmpwZw", icon: "fa-hands-clapping", desc: "Toggle appliances by clapping.", componentsList: ["Arduino Uno", "Sound Sensor Module", "Relay Module", "Breadboard", "Wires"], details: "Clap operated switch." },
  { id: 107, name: "Soil Moisture Alert", price: 550, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/0rDyJjAKymfBqdEY7QvELGBHGCioGQUOuO8-d8v8Iyg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc3F1YXJlc3Bh/Y2UtY2RuLmNvbS9j/b250ZW50L3YxLzU5/YjAzNzMwNGMwZGJm/YjA5MmZiZTg5NC8x/NTkyMjUyOTM5NTI1/LTFHWlU0ODdLQ0dZ/TjA5WEc2MU41L2Nh/cGFjaXRpdmVfc29p/bF9tb2lzdHVyZV9l/eHBlcmltZW50X3Nl/dHVwLkpQRw", icon: "fa-seedling", desc: "Beeps when your plant needs water.", componentsList: ["Arduino Uno", "Soil Moisture Sensor", "Buzzer", "LED", "9V Battery"], details: "Plant watering alert system." },
  { id: 108, name: "Laser Security Alarm", price: 450, category: "projects", rating: 4.6, image: "https://imgs.search.brave.com/1V9Ra3JC63YfQenqQaJ0kmyiO0Bat4Cx3xUGg5Re4TE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vc3JpdHVo/b2JieS5jb20vd3At/Y29udGVudC91cGxv/YWRzLzIwMjMvMTEv/MzQtMS5qcGc_cmVz/aXplPTkwMCw1MDUm/c3NsPTE", icon: "fa-shield-alt", desc: "Tripwire alarm using a laser beam.", componentsList: ["Arduino Uno", "Laser Diode", "LDR Sensor", "Buzzer", "Mirrors", "Wires"], details: "Laser tripwire security system." },
  { id: 109, name: "Heart Rate Monitor", price: 800, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/M9Sgi-l0_DXKP2ZzagUUMk6jWNMLzfT6qrnUsD_tEVc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZWxlY3Ryb25pY3Nm/b3J1LmNvbS93cC1j/b250ZW50cy91cGxv/YWRzLzIwMTkvMDYv/ZmlnMS01MDB4Mjkz/LnBuZw", icon: "fa-heartbeat", desc: "Measure pulse via fingertip.", componentsList: ["Arduino Uno", "Pulse Sensor", "OLED Display", "Breadboard", "Wires"], details: "Heart rate measuring device." },
  { id: 110, name: "Digital Dice", price: 300, category: "projects", rating: 4.4, image: "https://imgs.search.brave.com/OoLh0ANnt20K_9K4uQJ6IL-U-3xrkkChqaoVAuXA2xc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/c3Rlci5pbWdpeC5u/ZXQvdXBsb2Fkcy9h/dHRhY2htZW50cy8x/MzA1NTA1L19oSkhi/eXdPVlZZLmJsb2I_/YXV0bz1jb21wcmVz/cyxmb3JtYXQmdz00/MDAmaD0zMDAmZml0/PW1pbg", icon: "fa-dice", desc: "Push button to roll a random number.", componentsList: ["Arduino Uno", "7-Segment Display", "Push Button", "Resistors", "Breadboard", "Wires"], details: "Electronic digital dice." },
  { id: 111, name: "Alcohol Breathalyzer", price: 750, category: "projects", rating: 4.6, image: "https://imgs.search.brave.com/X-QpcNZ7zxbOrk7aW8RCtrqc0I8wSghNWw0HDwZ5vMc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/c3Rlci5pbWdpeC5u/ZXQvdXBsb2Fkcy9j/b3Zlcl9pbWFnZS9m/aWxlLzU5Mjg5L1ZJ/UEVSLWFsY29ob2xf/dGVzdF9pbWFnZS5q/cGc_YXV0bz1jb21w/cmVzcyxmb3JtYXQm/dz00MDAmaD0zMDAm/Zml0PW1pbg", icon: "fa-beer", desc: "Detect alcohol level in breath.", componentsList: ["Arduino Uno", "MQ-3 Alcohol Sensor", "16x2 LCD", "Buzzer", "LEDs", "Breadboard"], details: "Alcohol detection system." },
  { id: 112, name: "Smart Fan (Temp Control)", price: 850, category: "projects", rating: 4.7, image: "https://imgs.search.brave.com/fwhdKjKUT-BhVCfCsUa2W7yG5SX2Kt39mz9fgeO7Ssk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYWNr/c3Rlci5pbWdpeC5u/ZXQvdXBsb2Fkcy9h/dHRhY2htZW50cy8x/MTk4ODM1L19Ra044/NkdmanB2LmJsb2I_/YXV0bz1jb21wcmVz/cyxmb3JtYXQmdz05/MDAmaD02NzUmZml0/PW1pbg", icon: "fa-fan", desc: "Fan speed adjusts based on room temp.", componentsList: ["Arduino Uno", "LM35 Temp Sensor", "DC Motor", "L293D Driver", "LCD Display", "Wires"], details: "Temperature controlled fan." },
  { id: 113, name: "Piano (Piezo)", price: 350, category: "projects", rating: 4.3, image: "https://imgs.search.brave.com/i7RnQEc-j9ozuwnk7z-5vYrWO9jX0QjVWWTGS4lzLLk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50Lmluc3RydWN0/YWJsZXMuY29tL0ZK/MS9MRlZTL0tJMVBG/QUpBL0ZKMUxGVlNL/STFQRkFKQS5qcGc_/YXV0bz13ZWJwJmZp/dD1ib3VuZHMmZnJh/bWU9MSZoZWlnaHQ9/MTAyNCZ3aWR0aD0x/MDI0YXV0bz13ZWJw/JmZyYW1lPTEmaGVp/Z2h0PTMwMA", icon: "fa-music", desc: "Play notes using buttons.", componentsList: ["Arduino Uno", "Piezo Buzzer", "Push Buttons x4", "Resistors", "Breadboard", "Wires"], details: "Mini electronic piano." },
  { id: 114, name: "Calculator", price: 900, category: "projects", rating: 4.6, image: "https://imgs.search.brave.com/s0MBhLfjkOluGCXMO96xOs04IgPWHT5pet1a71H3aSI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jaXJj/dWl0ZGlnZXN0LmNv/bS9zaXRlcy9kZWZh/dWx0L2ZpbGVzL3By/b2plY3RpbWFnZV9t/aWMvQXJkdWluby1D/YWxjdWxhdG9yLXVz/aW5nLTR4NC1LZXlw/YWQuanBn", icon: "fa-calculator", desc: "Basic arithmetic operations.", componentsList: ["Arduino Uno", "4x4 Keypad", "16x2 LCD Display", "Potentiometer", "Wires"], details: "Arduino based calculator." },
  { id: 115, name: "Line Follower Robot", price: 1800, category: "projects", rating: 4.8, image: "https://imgs.search.brave.com/xKAmTEuaM2Yzm_NoOalWqKalHr88AGtY_ku0jg3fWiQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZWxlY3Ryb25pY3No/dWIub3JnL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE3LzAzL0Fy/ZHVpbm8tTGluZS1G/b2xsb3dlci1Sb2Jv/dC1JbWFnZS05LTc2/MHg0NDAuanBn", icon: "fa-road", desc: "Robot follows a black line on the floor.", componentsList: ["Arduino Uno", "IR Sensors x2", "L298N Driver", "Chassis", "BO Motors", "Battery"], details: "Line follower robot kit." },
  { id: 116, name: "RFID Attendance System", price: 1500, category: "projects", rating: 4.7, image: "https://imgs.search.brave.com/Tf5fW9D97iE_xKWlb66jBjgXW6EzzuyXoA6eODpz6ko/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jaXJj/dWl0ZGlnZXN0LmNv/bS9zaXRlcy9kZWZh/dWx0L2ZpbGVzL2lu/bGluZWltYWdlcy91/NS9QYXJ0cy1NYXJr/aW5nLW9mLVJGSUQt/UmVhZGVyLUFyZHVp/bm8tUHJvamVjdC5w/bmc", icon: "fa-id-badge", desc: "Log entry times to SD card or Serial.", componentsList: ["Arduino Uno", "RC522 RFID", "RTC Module", "SD Card Module", "LCD Display"], details: "Attendance system utilizing RFID." },
  { id: 118, name: "Water Quality Tester", price: 1100, category: "projects", rating: 4.5, image: "https://imgs.search.brave.com/EAXvNPX0bxiF_ci8raPlowjAuejBrfC9NtVn-anXjP0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/eGluZ29zb2Z0d2Fy/ZS5jb20vZWxla3Rv/ci9pbWFnZXMvZmV0/Y2gvZHByXzEsd184/MDAsaF80NjAsY19m/aXQvaHR0cHM6Ly93/d3cuZWxla3Rvcm1h/Z2F6aW5lLmNvbS9h/c3NldHMvdXBsb2Fk/L2ltYWdlcy8xLzIw/MjMxMTI4MTQ0NTU3/XzIzMDcxMS0wMTIt/OTQtT1JJR0lOQUwt/RmlndXJlLTkuanBn", icon: "fa-water", desc: "Measure TDS levels in water.", componentsList: ["Arduino Uno", "TDS Sensor Probe", "OLED Display", "Wires", "Breadboard"], details: "Water quality measurement kit." },

  // Kits
  { id: 201, name: "Arduino Starter Kit", price: 1850, category: "kits", rating: 4.9, image: "https://m.media-amazon.com/images/I/81KJPqDhpKL._SX425_.jpg", icon: "fa-box-open", desc: "The ultimate beginner's package to learn coding & electronics.", details: "Includes everything to get started:\n- Arduino Uno R3 (SMD)\n- Breadboard & Jumper Wires\n- USB Cable\n- Assorted LEDs (Red, Green, Yellow)\n- Resistor Pack (Mixed Values)\n- Push Buttons & Buzzers\n- Light Sensor (LDR)\n- Sturdy Plastic Storage Box" },
  { id: 202, name: "Electronic Tools Starter Kit", price: 1850, category: "kits", rating: 4.9, image: "https://m.media-amazon.com/images/I/51JN1WGrq7L.jpg", icon: "fa-box-open", desc: "The ultimate beginner's package for soldering and testing.", details: "Includes everything to get started:\nMultimeter.\nSoldering full Kit\nSturdy and Reliable" }
];